// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chatpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2SLogin struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLogin) Reset()         { *m = C2SLogin{} }
func (m *C2SLogin) String() string { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()    {}
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *C2SLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLogin.Unmarshal(m, b)
}
func (m *C2SLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLogin.Marshal(b, m, deterministic)
}
func (m *C2SLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLogin.Merge(m, src)
}
func (m *C2SLogin) XXX_Size() int {
	return xxx_messageInfo_C2SLogin.Size(m)
}
func (m *C2SLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLogin proto.InternalMessageInfo

func (m *C2SLogin) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *C2SLogin) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type S2CLogin struct {
	ERet                 ERetType `protobuf:"varint,1,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CLogin) Reset()         { *m = S2CLogin{} }
func (m *S2CLogin) String() string { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()    {}
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *S2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLogin.Unmarshal(m, b)
}
func (m *S2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLogin.Marshal(b, m, deterministic)
}
func (m *S2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLogin.Merge(m, src)
}
func (m *S2CLogin) XXX_Size() int {
	return xxx_messageInfo_S2CLogin.Size(m)
}
func (m *S2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLogin proto.InternalMessageInfo

func (m *S2CLogin) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

type C2SRegister struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SRegister) Reset()         { *m = C2SRegister{} }
func (m *C2SRegister) String() string { return proto.CompactTextString(m) }
func (*C2SRegister) ProtoMessage()    {}
func (*C2SRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *C2SRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SRegister.Unmarshal(m, b)
}
func (m *C2SRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SRegister.Marshal(b, m, deterministic)
}
func (m *C2SRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SRegister.Merge(m, src)
}
func (m *C2SRegister) XXX_Size() int {
	return xxx_messageInfo_C2SRegister.Size(m)
}
func (m *C2SRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SRegister.DiscardUnknown(m)
}

var xxx_messageInfo_C2SRegister proto.InternalMessageInfo

func (m *C2SRegister) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *C2SRegister) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type S2CRegister struct {
	ERet                 ERetType `protobuf:"varint,1,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRegister) Reset()         { *m = S2CRegister{} }
func (m *S2CRegister) String() string { return proto.CompactTextString(m) }
func (*S2CRegister) ProtoMessage()    {}
func (*S2CRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *S2CRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRegister.Unmarshal(m, b)
}
func (m *S2CRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRegister.Marshal(b, m, deterministic)
}
func (m *S2CRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRegister.Merge(m, src)
}
func (m *S2CRegister) XXX_Size() int {
	return xxx_messageInfo_S2CRegister.Size(m)
}
func (m *S2CRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRegister.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRegister proto.InternalMessageInfo

func (m *S2CRegister) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "chatpb.C2SLogin")
	proto.RegisterType((*S2CLogin)(nil), "chatpb.S2CLogin")
	proto.RegisterType((*C2SRegister)(nil), "chatpb.C2SRegister")
	proto.RegisterType((*S2CRegister)(nil), "chatpb.S2CRegister")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0xa4, 0x78, 0x92, 0xf3,
	0x73, 0x73, 0xf3, 0xf3, 0x20, 0xa2, 0x4a, 0x4e, 0x5c, 0x1c, 0xce, 0x46, 0xc1, 0x3e, 0xf9, 0xe9,
	0x99, 0x79, 0x42, 0x52, 0x5c, 0x1c, 0xa5, 0xc5, 0xa9, 0x45, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x70, 0x3e, 0x48, 0xae, 0x20, 0xb1, 0xb8, 0xb8, 0x3c, 0xbf, 0x28,
	0x45, 0x82, 0x09, 0x22, 0x07, 0xe3, 0x2b, 0x19, 0x70, 0x71, 0x04, 0x1b, 0x39, 0x43, 0xcc, 0x50,
	0xe1, 0x62, 0x49, 0x0d, 0x4a, 0x2d, 0x01, 0xeb, 0xe7, 0x33, 0x12, 0xd0, 0x83, 0x58, 0xaa, 0xe7,
	0x1a, 0x94, 0x5a, 0x12, 0x52, 0x59, 0x90, 0x1a, 0x04, 0x96, 0x55, 0x72, 0xe5, 0xe2, 0x76, 0x36,
	0x0a, 0x0e, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0x22, 0xdb, 0x62, 0x63, 0x2e, 0xee, 0x60,
	0x23, 0x67, 0xb8, 0x31, 0x44, 0xd9, 0x9d, 0xc4, 0x06, 0xf6, 0xb8, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x0e, 0x8d, 0xa8, 0xa1, 0x1c, 0x01, 0x00, 0x00,
}
