// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chatpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type C2SLogin struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SLogin) Reset()         { *m = C2SLogin{} }
func (m *C2SLogin) String() string { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()    {}
func (*C2SLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *C2SLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SLogin.Unmarshal(m, b)
}
func (m *C2SLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SLogin.Marshal(b, m, deterministic)
}
func (m *C2SLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SLogin.Merge(m, src)
}
func (m *C2SLogin) XXX_Size() int {
	return xxx_messageInfo_C2SLogin.Size(m)
}
func (m *C2SLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2SLogin proto.InternalMessageInfo

func (m *C2SLogin) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *C2SLogin) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type S2CLogin struct {
	ERet                 ERetType    `protobuf:"varint,1,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	Info                 *StructUser `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Lastchat             [][]byte    `protobuf:"bytes,3,rep,name=lastchat,proto3" json:"lastchat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2CLogin) Reset()         { *m = S2CLogin{} }
func (m *S2CLogin) String() string { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()    {}
func (*S2CLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *S2CLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CLogin.Unmarshal(m, b)
}
func (m *S2CLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CLogin.Marshal(b, m, deterministic)
}
func (m *S2CLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CLogin.Merge(m, src)
}
func (m *S2CLogin) XXX_Size() int {
	return xxx_messageInfo_S2CLogin.Size(m)
}
func (m *S2CLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CLogin.DiscardUnknown(m)
}

var xxx_messageInfo_S2CLogin proto.InternalMessageInfo

func (m *S2CLogin) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

func (m *S2CLogin) GetInfo() *StructUser {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *S2CLogin) GetLastchat() [][]byte {
	if m != nil {
		return m.Lastchat
	}
	return nil
}

type C2SRegister struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             []byte   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SRegister) Reset()         { *m = C2SRegister{} }
func (m *C2SRegister) String() string { return proto.CompactTextString(m) }
func (*C2SRegister) ProtoMessage()    {}
func (*C2SRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *C2SRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SRegister.Unmarshal(m, b)
}
func (m *C2SRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SRegister.Marshal(b, m, deterministic)
}
func (m *C2SRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SRegister.Merge(m, src)
}
func (m *C2SRegister) XXX_Size() int {
	return xxx_messageInfo_C2SRegister.Size(m)
}
func (m *C2SRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SRegister.DiscardUnknown(m)
}

var xxx_messageInfo_C2SRegister proto.InternalMessageInfo

func (m *C2SRegister) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *C2SRegister) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

type S2CRegister struct {
	ERet                 ERetType `protobuf:"varint,1,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CRegister) Reset()         { *m = S2CRegister{} }
func (m *S2CRegister) String() string { return proto.CompactTextString(m) }
func (*S2CRegister) ProtoMessage()    {}
func (*S2CRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *S2CRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CRegister.Unmarshal(m, b)
}
func (m *S2CRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CRegister.Marshal(b, m, deterministic)
}
func (m *S2CRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CRegister.Merge(m, src)
}
func (m *S2CRegister) XXX_Size() int {
	return xxx_messageInfo_S2CRegister.Size(m)
}
func (m *S2CRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CRegister.DiscardUnknown(m)
}

var xxx_messageInfo_S2CRegister proto.InternalMessageInfo

func (m *S2CRegister) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

type C2SOnlineUsers struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SOnlineUsers) Reset()         { *m = C2SOnlineUsers{} }
func (m *C2SOnlineUsers) String() string { return proto.CompactTextString(m) }
func (*C2SOnlineUsers) ProtoMessage()    {}
func (*C2SOnlineUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *C2SOnlineUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SOnlineUsers.Unmarshal(m, b)
}
func (m *C2SOnlineUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SOnlineUsers.Marshal(b, m, deterministic)
}
func (m *C2SOnlineUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SOnlineUsers.Merge(m, src)
}
func (m *C2SOnlineUsers) XXX_Size() int {
	return xxx_messageInfo_C2SOnlineUsers.Size(m)
}
func (m *C2SOnlineUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SOnlineUsers.DiscardUnknown(m)
}

var xxx_messageInfo_C2SOnlineUsers proto.InternalMessageInfo

type S2COnlineUsers struct {
	Users                []*StructUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	ERet                 ERetType      `protobuf:"varint,2,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S2COnlineUsers) Reset()         { *m = S2COnlineUsers{} }
func (m *S2COnlineUsers) String() string { return proto.CompactTextString(m) }
func (*S2COnlineUsers) ProtoMessage()    {}
func (*S2COnlineUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *S2COnlineUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2COnlineUsers.Unmarshal(m, b)
}
func (m *S2COnlineUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2COnlineUsers.Marshal(b, m, deterministic)
}
func (m *S2COnlineUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2COnlineUsers.Merge(m, src)
}
func (m *S2COnlineUsers) XXX_Size() int {
	return xxx_messageInfo_S2COnlineUsers.Size(m)
}
func (m *S2COnlineUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_S2COnlineUsers.DiscardUnknown(m)
}

var xxx_messageInfo_S2COnlineUsers proto.InternalMessageInfo

func (m *S2COnlineUsers) GetUsers() []*StructUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *S2COnlineUsers) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

type C2SChat struct {
	EMsgType             EMsgType `protobuf:"varint,1,opt,name=eMsgType,proto3,enum=chatpb.EMsgType" json:"eMsgType,omitempty"`
	ToUid                int32    `protobuf:"varint,2,opt,name=toUid,proto3" json:"toUid,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	ToNick               []byte   `protobuf:"bytes,4,opt,name=toNick,proto3" json:"toNick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChat) Reset()         { *m = C2SChat{} }
func (m *C2SChat) String() string { return proto.CompactTextString(m) }
func (*C2SChat) ProtoMessage()    {}
func (*C2SChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{6}
}

func (m *C2SChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChat.Unmarshal(m, b)
}
func (m *C2SChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChat.Marshal(b, m, deterministic)
}
func (m *C2SChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChat.Merge(m, src)
}
func (m *C2SChat) XXX_Size() int {
	return xxx_messageInfo_C2SChat.Size(m)
}
func (m *C2SChat) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChat.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChat proto.InternalMessageInfo

func (m *C2SChat) GetEMsgType() EMsgType {
	if m != nil {
		return m.EMsgType
	}
	return EMsgType_eMsg_All
}

func (m *C2SChat) GetToUid() int32 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *C2SChat) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *C2SChat) GetToNick() []byte {
	if m != nil {
		return m.ToNick
	}
	return nil
}

type S2CChat struct {
	EMsgType             EMsgType `protobuf:"varint,1,opt,name=eMsgType,proto3,enum=chatpb.EMsgType" json:"eMsgType,omitempty"`
	FromUid              int32    `protobuf:"varint,2,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	Msg                  []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	ERet                 ERetType `protobuf:"varint,4,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	ToUid                int32    `protobuf:"varint,5,opt,name=toUid,proto3" json:"toUid,omitempty"`
	FromNick             []byte   `protobuf:"bytes,6,opt,name=fromNick,proto3" json:"fromNick,omitempty"`
	ToNick               []byte   `protobuf:"bytes,7,opt,name=toNick,proto3" json:"toNick,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2CChat) Reset()         { *m = S2CChat{} }
func (m *S2CChat) String() string { return proto.CompactTextString(m) }
func (*S2CChat) ProtoMessage()    {}
func (*S2CChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{7}
}

func (m *S2CChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChat.Unmarshal(m, b)
}
func (m *S2CChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChat.Marshal(b, m, deterministic)
}
func (m *S2CChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChat.Merge(m, src)
}
func (m *S2CChat) XXX_Size() int {
	return xxx_messageInfo_S2CChat.Size(m)
}
func (m *S2CChat) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChat.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChat proto.InternalMessageInfo

func (m *S2CChat) GetEMsgType() EMsgType {
	if m != nil {
		return m.EMsgType
	}
	return EMsgType_eMsg_All
}

func (m *S2CChat) GetFromUid() int32 {
	if m != nil {
		return m.FromUid
	}
	return 0
}

func (m *S2CChat) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *S2CChat) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

func (m *S2CChat) GetToUid() int32 {
	if m != nil {
		return m.ToUid
	}
	return 0
}

func (m *S2CChat) GetFromNick() []byte {
	if m != nil {
		return m.FromNick
	}
	return nil
}

func (m *S2CChat) GetToNick() []byte {
	if m != nil {
		return m.ToNick
	}
	return nil
}

type C2SChatCntTopUsers struct {
	Start                int32    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Cnt                  int32    `protobuf:"varint,2,opt,name=cnt,proto3" json:"cnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SChatCntTopUsers) Reset()         { *m = C2SChatCntTopUsers{} }
func (m *C2SChatCntTopUsers) String() string { return proto.CompactTextString(m) }
func (*C2SChatCntTopUsers) ProtoMessage()    {}
func (*C2SChatCntTopUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{8}
}

func (m *C2SChatCntTopUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SChatCntTopUsers.Unmarshal(m, b)
}
func (m *C2SChatCntTopUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SChatCntTopUsers.Marshal(b, m, deterministic)
}
func (m *C2SChatCntTopUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SChatCntTopUsers.Merge(m, src)
}
func (m *C2SChatCntTopUsers) XXX_Size() int {
	return xxx_messageInfo_C2SChatCntTopUsers.Size(m)
}
func (m *C2SChatCntTopUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SChatCntTopUsers.DiscardUnknown(m)
}

var xxx_messageInfo_C2SChatCntTopUsers proto.InternalMessageInfo

func (m *C2SChatCntTopUsers) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *C2SChatCntTopUsers) GetCnt() int32 {
	if m != nil {
		return m.Cnt
	}
	return 0
}

type S2CChatCntTopUsers struct {
	Users                []*StructUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	ERet                 ERetType      `protobuf:"varint,2,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S2CChatCntTopUsers) Reset()         { *m = S2CChatCntTopUsers{} }
func (m *S2CChatCntTopUsers) String() string { return proto.CompactTextString(m) }
func (*S2CChatCntTopUsers) ProtoMessage()    {}
func (*S2CChatCntTopUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{9}
}

func (m *S2CChatCntTopUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CChatCntTopUsers.Unmarshal(m, b)
}
func (m *S2CChatCntTopUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CChatCntTopUsers.Marshal(b, m, deterministic)
}
func (m *S2CChatCntTopUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CChatCntTopUsers.Merge(m, src)
}
func (m *S2CChatCntTopUsers) XXX_Size() int {
	return xxx_messageInfo_S2CChatCntTopUsers.Size(m)
}
func (m *S2CChatCntTopUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CChatCntTopUsers.DiscardUnknown(m)
}

var xxx_messageInfo_S2CChatCntTopUsers proto.InternalMessageInfo

func (m *S2CChatCntTopUsers) GetUsers() []*StructUser {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *S2CChatCntTopUsers) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

type S2CStatusChange struct {
	User                 *StructUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               EUserStatus `protobuf:"varint,2,opt,name=status,proto3,enum=chatpb.EUserStatus" json:"status,omitempty"`
	ERet                 ERetType    `protobuf:"varint,3,opt,name=eRet,proto3,enum=chatpb.ERetType" json:"eRet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *S2CStatusChange) Reset()         { *m = S2CStatusChange{} }
func (m *S2CStatusChange) String() string { return proto.CompactTextString(m) }
func (*S2CStatusChange) ProtoMessage()    {}
func (*S2CStatusChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{10}
}

func (m *S2CStatusChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2CStatusChange.Unmarshal(m, b)
}
func (m *S2CStatusChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2CStatusChange.Marshal(b, m, deterministic)
}
func (m *S2CStatusChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2CStatusChange.Merge(m, src)
}
func (m *S2CStatusChange) XXX_Size() int {
	return xxx_messageInfo_S2CStatusChange.Size(m)
}
func (m *S2CStatusChange) XXX_DiscardUnknown() {
	xxx_messageInfo_S2CStatusChange.DiscardUnknown(m)
}

var xxx_messageInfo_S2CStatusChange proto.InternalMessageInfo

func (m *S2CStatusChange) GetUser() *StructUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *S2CStatusChange) GetStatus() EUserStatus {
	if m != nil {
		return m.Status
	}
	return EUserStatus_eStatus_Online
}

func (m *S2CStatusChange) GetERet() ERetType {
	if m != nil {
		return m.ERet
	}
	return ERetType_Success
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "chatpb.C2SLogin")
	proto.RegisterType((*S2CLogin)(nil), "chatpb.S2CLogin")
	proto.RegisterType((*C2SRegister)(nil), "chatpb.C2SRegister")
	proto.RegisterType((*S2CRegister)(nil), "chatpb.S2CRegister")
	proto.RegisterType((*C2SOnlineUsers)(nil), "chatpb.C2SOnlineUsers")
	proto.RegisterType((*S2COnlineUsers)(nil), "chatpb.S2COnlineUsers")
	proto.RegisterType((*C2SChat)(nil), "chatpb.C2SChat")
	proto.RegisterType((*S2CChat)(nil), "chatpb.S2CChat")
	proto.RegisterType((*C2SChatCntTopUsers)(nil), "chatpb.C2SChatCntTopUsers")
	proto.RegisterType((*S2CChatCntTopUsers)(nil), "chatpb.S2CChatCntTopUsers")
	proto.RegisterType((*S2CStatusChange)(nil), "chatpb.S2CStatusChange")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6b, 0xdc, 0x30,
	0x10, 0xc5, 0xf1, 0xda, 0x6b, 0x66, 0xc3, 0x76, 0x51, 0x43, 0x31, 0x7b, 0x5a, 0x4c, 0x29, 0x81,
	0x96, 0x3d, 0x28, 0xd7, 0x9e, 0x2a, 0x72, 0xeb, 0x07, 0x48, 0xc9, 0xbd, 0x8e, 0xa3, 0x78, 0x4d,
	0x63, 0xc9, 0x58, 0xb3, 0x84, 0xfe, 0x87, 0xfe, 0xbb, 0xfe, 0xa1, 0x32, 0x92, 0xed, 0x6e, 0x69,
	0xb3, 0x94, 0x90, 0x9b, 0xde, 0xcc, 0x68, 0xde, 0x7b, 0x33, 0x96, 0x01, 0xaa, 0x5d, 0x89, 0xdb,
	0xae, 0xb7, 0x68, 0x59, 0x4a, 0xe7, 0xee, 0x66, 0x7d, 0x5a, 0xd9, 0xb6, 0xb5, 0x26, 0x44, 0x8b,
	0x0f, 0x90, 0x09, 0xae, 0x3e, 0xda, 0xba, 0x31, 0x6c, 0x0d, 0xd9, 0xde, 0xe9, 0xde, 0x94, 0xad,
	0xce, 0xa3, 0x4d, 0x74, 0x7e, 0x2a, 0x27, 0x4c, 0xb9, 0xae, 0x74, 0xee, 0xc1, 0xf6, 0xb7, 0xf9,
	0x49, 0xc8, 0x8d, 0xb8, 0x40, 0xc8, 0x14, 0x17, 0xa1, 0xc7, 0x6b, 0x98, 0x69, 0xa9, 0xd1, 0xdf,
	0x5f, 0xf2, 0xd5, 0x36, 0x90, 0x6e, 0x2f, 0xa5, 0xc6, 0xab, 0xef, 0x9d, 0x96, 0x3e, 0xcb, 0xde,
	0xc0, 0xac, 0x31, 0x77, 0xd6, 0x77, 0x5a, 0x70, 0x36, 0x56, 0x29, 0xec, 0xf7, 0x15, 0x5e, 0x3b,
	0xdd, 0x4b, 0x9f, 0x27, 0xd6, 0xfb, 0xd2, 0x21, 0xa5, 0xf3, 0x78, 0x13, 0x13, 0xeb, 0x88, 0x8b,
	0x4b, 0x58, 0x08, 0xae, 0xa4, 0xae, 0x1b, 0x87, 0xba, 0x7f, 0xb2, 0xf8, 0x0b, 0x58, 0x28, 0x2e,
	0xa6, 0x36, 0xff, 0xa5, 0xbf, 0x58, 0xc1, 0x52, 0x70, 0xf5, 0xc5, 0xdc, 0x37, 0x46, 0x93, 0x5c,
	0x57, 0x7c, 0x85, 0xa5, 0xe2, 0xe2, 0x20, 0xc2, 0xce, 0x21, 0x21, 0x01, 0x2e, 0x8f, 0x36, 0xf1,
	0x23, 0x26, 0x43, 0xc1, 0xc4, 0x79, 0x72, 0x94, 0xf3, 0x01, 0xe6, 0x82, 0x2b, 0xb1, 0x2b, 0x91,
	0xbd, 0x83, 0x4c, 0x7f, 0x72, 0x35, 0x25, 0xff, 0x12, 0x3a, 0xc4, 0xe5, 0x54, 0xc1, 0xce, 0x20,
	0x41, 0x7b, 0xdd, 0x04, 0xeb, 0x89, 0x0c, 0x80, 0xad, 0x20, 0x6e, 0x5d, 0x9d, 0xc7, 0x7e, 0x1c,
	0x74, 0x64, 0xaf, 0x20, 0x45, 0xfb, 0xb9, 0xa9, 0xbe, 0xe5, 0x33, 0x1f, 0x1c, 0x50, 0xf1, 0x33,
	0x82, 0xb9, 0xe2, 0xe2, 0x09, 0xcc, 0x39, 0xcc, 0xef, 0x7a, 0xdb, 0xfe, 0xe6, 0x1e, 0xe1, 0x3f,
	0xd8, 0xc7, 0x21, 0xcc, 0x8e, 0x7e, 0x38, 0x93, 0x97, 0xe4, 0xd0, 0xcb, 0x1a, 0x32, 0x6a, 0xec,
	0xb5, 0xa7, 0x61, 0xbf, 0x23, 0x3e, 0x70, 0x35, 0xff, 0xc3, 0xd5, 0x7b, 0x60, 0xc3, 0x38, 0x85,
	0xc1, 0x2b, 0xdb, 0x85, 0xa5, 0x9d, 0x41, 0xe2, 0xb0, 0xec, 0xc3, 0xfe, 0x13, 0x19, 0x00, 0xa9,
	0xad, 0x0c, 0x0e, 0x1e, 0xe8, 0x58, 0xdc, 0x02, 0x1b, 0x46, 0x72, 0x78, 0xfb, 0xb9, 0x57, 0xfe,
	0x23, 0x82, 0x17, 0x8a, 0x0b, 0x85, 0x25, 0xee, 0x9d, 0xd8, 0x95, 0xa6, 0xd6, 0xf4, 0x74, 0xa8,
	0x85, 0x17, 0xf8, 0xc8, 0xd3, 0xa1, 0x3c, 0x7b, 0x0b, 0xa9, 0xf3, 0xf7, 0x06, 0x8e, 0x97, 0x13,
	0x07, 0x15, 0x85, 0x96, 0x72, 0x28, 0x99, 0xe4, 0xc4, 0xc7, 0xe4, 0xdc, 0xa4, 0xfe, 0x97, 0x71,
	0xf1, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x16, 0xe8, 0x63, 0x5e, 0x56, 0x04, 0x00, 0x00,
}
