// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package chatpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ERetType int32

const (
	ERetType_Success       ERetType = 0
	ERetType_NormalError   ERetType = 1
	ERetType_RedisError    ERetType = 2
	ERetType_SQLError      ERetType = 3
	ERetType_PwError       ERetType = 100
	ERetType_UnError       ERetType = 101
	ERetType_UnExistError  ERetType = 102
	ERetType_UnNotStandard ERetType = 103
	ERetType_PwNotStandard ERetType = 104
	ERetType_UserOffline   ERetType = 105
)

var ERetType_name = map[int32]string{
	0:   "Success",
	1:   "NormalError",
	2:   "RedisError",
	3:   "SQLError",
	100: "PwError",
	101: "UnError",
	102: "UnExistError",
	103: "UnNotStandard",
	104: "PwNotStandard",
	105: "UserOffline",
}

var ERetType_value = map[string]int32{
	"Success":       0,
	"NormalError":   1,
	"RedisError":    2,
	"SQLError":      3,
	"PwError":       100,
	"UnError":       101,
	"UnExistError":  102,
	"UnNotStandard": 103,
	"PwNotStandard": 104,
	"UserOffline":   105,
}

func (x ERetType) String() string {
	return proto.EnumName(ERetType_name, int32(x))
}

func (ERetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type EMsgType int32

const (
	EMsgType_eMsg_All EMsgType = 0
	EMsgType_eMsg_One EMsgType = 1
)

var EMsgType_name = map[int32]string{
	0: "eMsg_All",
	1: "eMsg_One",
}

var EMsgType_value = map[string]int32{
	"eMsg_All": 0,
	"eMsg_One": 1,
}

func (x EMsgType) String() string {
	return proto.EnumName(EMsgType_name, int32(x))
}

func (EMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type EUserStatus int32

const (
	EUserStatus_eStatus_Online  EUserStatus = 0
	EUserStatus_eStatus_Offline EUserStatus = 1
)

var EUserStatus_name = map[int32]string{
	0: "eStatus_Online",
	1: "eStatus_Offline",
}

var EUserStatus_value = map[string]int32{
	"eStatus_Online":  0,
	"eStatus_Offline": 1,
}

func (x EUserStatus) String() string {
	return proto.EnumName(EUserStatus_name, int32(x))
}

func (EUserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

type StructUser struct {
	Username             []byte   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Uid                  int32    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Regtime              int64    `protobuf:"varint,3,opt,name=regtime,proto3" json:"regtime,omitempty"`
	Lastlogintime        int64    `protobuf:"varint,4,opt,name=lastlogintime,proto3" json:"lastlogintime,omitempty"`
	Chatcnt              int32    `protobuf:"varint,5,opt,name=chatcnt,proto3" json:"chatcnt,omitempty"`
	Lastleavetime        int64    `protobuf:"varint,6,opt,name=lastleavetime,proto3" json:"lastleavetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StructUser) Reset()         { *m = StructUser{} }
func (m *StructUser) String() string { return proto.CompactTextString(m) }
func (*StructUser) ProtoMessage()    {}
func (*StructUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *StructUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructUser.Unmarshal(m, b)
}
func (m *StructUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructUser.Marshal(b, m, deterministic)
}
func (m *StructUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructUser.Merge(m, src)
}
func (m *StructUser) XXX_Size() int {
	return xxx_messageInfo_StructUser.Size(m)
}
func (m *StructUser) XXX_DiscardUnknown() {
	xxx_messageInfo_StructUser.DiscardUnknown(m)
}

var xxx_messageInfo_StructUser proto.InternalMessageInfo

func (m *StructUser) GetUsername() []byte {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *StructUser) GetUid() int32 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *StructUser) GetRegtime() int64 {
	if m != nil {
		return m.Regtime
	}
	return 0
}

func (m *StructUser) GetLastlogintime() int64 {
	if m != nil {
		return m.Lastlogintime
	}
	return 0
}

func (m *StructUser) GetChatcnt() int32 {
	if m != nil {
		return m.Chatcnt
	}
	return 0
}

func (m *StructUser) GetLastleavetime() int64 {
	if m != nil {
		return m.Lastleavetime
	}
	return 0
}

func init() {
	proto.RegisterEnum("chatpb.ERetType", ERetType_name, ERetType_value)
	proto.RegisterEnum("chatpb.EMsgType", EMsgType_name, EMsgType_value)
	proto.RegisterEnum("chatpb.EUserStatus", EUserStatus_name, EUserStatus_value)
	proto.RegisterType((*StructUser)(nil), "chatpb.StructUser")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x6e, 0xea, 0x30,
	0x10, 0x85, 0x31, 0xb9, 0x40, 0x34, 0x04, 0xc8, 0xf5, 0xdd, 0x44, 0x77, 0x85, 0xaa, 0xaa, 0x42,
	0x2c, 0xba, 0xa9, 0xd4, 0x7d, 0x17, 0xd9, 0x95, 0x9f, 0x26, 0xcd, 0x1a, 0x99, 0x64, 0x08, 0x96,
	0x12, 0x1b, 0xd9, 0x4e, 0x69, 0x1f, 0xa9, 0xaf, 0xd0, 0xa7, 0xab, 0xec, 0x94, 0x88, 0xee, 0xe6,
	0x3b, 0xa3, 0x6f, 0x74, 0x12, 0x43, 0x90, 0xcb, 0xba, 0x96, 0xe2, 0xfe, 0xa4, 0xa4, 0x91, 0x74,
	0x98, 0x1f, 0x99, 0x39, 0xed, 0x6f, 0xbe, 0x08, 0x40, 0x6a, 0x54, 0x93, 0x9b, 0x4c, 0xa3, 0xa2,
	0xff, 0xc1, 0x6f, 0x34, 0x2a, 0xc1, 0x6a, 0x8c, 0xc8, 0x9c, 0x2c, 0x82, 0xa4, 0x63, 0x1a, 0x82,
	0xd7, 0xf0, 0x22, 0xea, 0xcf, 0xc9, 0x62, 0x90, 0xd8, 0x91, 0x46, 0x30, 0x52, 0x58, 0x1a, 0x5e,
	0x63, 0xe4, 0xcd, 0xc9, 0xc2, 0x4b, 0x2e, 0x48, 0x6f, 0x61, 0x52, 0x31, 0x6d, 0x2a, 0x59, 0x72,
	0xe1, 0xf6, 0x7f, 0xdc, 0xfe, 0x77, 0x68, 0x7d, 0x5b, 0x23, 0x17, 0x26, 0x1a, 0xb8, 0xab, 0x17,
	0xec, 0x7c, 0x64, 0x6f, 0xe8, 0xfc, 0xe1, 0x95, 0x7f, 0x09, 0x97, 0x9f, 0x04, 0xfc, 0x38, 0x41,
	0xf3, 0xfa, 0x71, 0x42, 0x3a, 0x86, 0x51, 0xda, 0xe4, 0x39, 0x6a, 0x1d, 0xf6, 0xe8, 0x0c, 0xc6,
	0x6b, 0xa9, 0x6a, 0x56, 0xc5, 0x4a, 0x49, 0x15, 0x12, 0x3a, 0x05, 0x48, 0xb0, 0xe0, 0xba, 0xe5,
	0x3e, 0x0d, 0xc0, 0x4f, 0x5f, 0x9e, 0x5b, 0xf2, 0xac, 0xbb, 0x3d, 0xb7, 0x50, 0x58, 0xc8, 0x44,
	0x0b, 0xf6, 0xa3, 0x83, 0x4c, 0xc4, 0xef, 0x5c, 0x9b, 0x36, 0x39, 0xd0, 0xbf, 0x30, 0xc9, 0xc4,
	0x5a, 0x9a, 0xd4, 0x30, 0x51, 0x30, 0x55, 0x84, 0xa5, 0x8d, 0xb6, 0xe7, 0xeb, 0xe8, 0x68, 0x0b,
	0xd8, 0x1f, 0xba, 0x39, 0x1c, 0x2a, 0x2e, 0x30, 0xe4, 0xcb, 0x3b, 0xf0, 0xe3, 0x95, 0x2e, 0x5d,
	0xd5, 0x00, 0x7c, 0x5c, 0xe9, 0x72, 0xf7, 0x54, 0x55, 0x61, 0xaf, 0xa3, 0x8d, 0xc0, 0x90, 0x2c,
	0x1f, 0x61, 0x1c, 0x5b, 0x33, 0x35, 0xcc, 0x34, 0x9a, 0x52, 0x98, 0x62, 0x3b, 0xee, 0x36, 0xc2,
	0x9d, 0xea, 0xd1, 0x7f, 0x30, 0xeb, 0xb2, 0x9f, 0xfb, 0x64, 0x3f, 0x74, 0xef, 0xfa, 0xf0, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x4f, 0xda, 0xb3, 0xa2, 0xe7, 0x01, 0x00, 0x00,
}
